## 6.3

In [ ]:
import numpy as np

theta = np.array([[0.44000000], [-0.93000000], [-0.30000000], [-0.65000000], [0.16000000], [0.11000000], [-0.54000000], [0.45000000]])
dtheta = np.array([[-0.25000000], [-0.38000000], [-0.75000000], [0.05000000], [0.59000000], [-0.95000000], [0.09000000], [-0.67000000]])
jacobian = np.array([[0.00000000, 0.00000000, 0.00000000, -0.41687080, -0.41687080,  0.00000000, 0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, -0.90896575, -0.90896575,  0.00000000, 0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, -1.00000000,  -1.00000000, 0.00000000], [-0.41687080, 0.80201035, -0.42778281, 5.45379450, 5.45379450,  4.16541736, 2.45000000, 0.00000000], [-0.90896575, -0.36781881, 0.19619019, -2.50122481, -2.50122481,  -1.02827198, -0.00000000, 1.00000000], [0.00000000, 0.47062589, 0.88233286, -0.80177686, -0.80177686,  -0.00000000, 0.00000000, 0.00000000]])
T_1in0 = np.array([[-0.42778281, 0.19619019, 0.88233286, 0.78333980], [-0.41687080, -0.90896575, 0.00000000, 2.22512172], [0.80201035, -0.36781881, 0.47062589, -4.46118940], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [ ]:
ans= jacobian@dtheta
ans #v010

array([[-0.26679731],
       [-0.58173808],
       [ 0.86      ],
       [-0.12592714],
       [-1.07405555],
       [-1.35372467]])

In [ ]:
import numpy as np

theta = np.array([[-0.83000000], [-0.52000000], [-0.07000000], [-0.53000000], [-0.72000000], [0.46000000], [-0.39000000], [0.54000000], [-0.82000000]])
dtheta = np.array([[0.07000000], [0.41000000], [0.22000000], [0.13000000], [-0.59000000], [-0.60000000], [0.67000000], [0.31000000], [0.95000000]])
jacobian = np.array([[0.95620882, -0.24235249, -0.91135612, -0.26502958, -0.62711013,  0.00000000, 0.00000000, -0.68222121, 0.00000000], [0.28287328, 0.62126764, 0.11761695, 0.56555996, 0.51413599, 0.00000000,  0.00000000, -0.00000000, 1.00000000], [0.07514916, 0.74517903, -0.39445693, 0.78096175, -0.58514705,  0.00000000, 0.00000000, 0.73114583, 0.00000000], [-0.12536133, -3.06546241, 2.49329546, -1.02418829, 5.36289360,  0.62711013, 0.37590839, -1.46229166, 2.00000000], [-1.51349398, 2.18913975, 3.23960354, 3.72566725, 1.25422025,  -0.51413599, 0.85770868, 3.36444241, -0.00000000], [7.29214580, -2.82209247, -4.79456096, -3.04564009, -4.64547347,  0.58514705, 0.35075448, -1.36444241, -0.00000000]])
T_1in0 = np.array([[0.04246070, 0.11997178, -0.99186887, -0.65501997], [-0.95620882, -0.28287328, -0.07514916, -5.97275287], [-0.28958898, 0.95162465, 0.10270707, 7.41975193], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [ ]:
ans= jacobian@dtheta
ans #v010

array([[-0.10887569],
       [ 1.02057915],
       [ 0.89742031],
       [-2.69205945],
       [ 3.17478585],
       [ 0.10442514]])

In [ ]:
import numpy as np

theta = np.array([[-0.67000000], [0.74000000], [-1.00000000], [0.92000000], [-0.91000000], [0.77000000], [0.90000000]])
dtheta = np.array([[-0.88000000], [-0.38000000], [-0.18000000], [0.85000000], [-0.36000000], [0.38000000], [0.19000000]])
jacobian = np.array([[0.00000000, 0.56679316, 0.00000000, 0.00000000, -0.69613524,  -0.00000000, 0.00000000], [0.00000000, 0.54960137, 0.00000000, 0.00000000, 0.71791067, -0.00000000,  0.00000000], [0.00000000, 0.61374575, 0.00000000, 0.00000000, -0.00000000,  -1.00000000, 0.00000000], [0.56679316, -5.96336778, -0.69613524, -0.56679316, -1.43582134,  2.90000000, -0.00000000], [0.54960137, -1.85716399, 0.71791067, -0.54960137, -1.39227048,  -0.00000000, 1.00000000], [0.61374575, 7.17022634, -0.00000000, -0.61374575, -2.01879219,  -0.00000000, 0.00000000]])
T_1in0 = np.array([[0.79477562, -0.16856776, -0.58302369, -4.04281451], [0.21697287, -0.81824400, 0.53235283, -4.60689316], [-0.56679316, -0.54960137, -0.61374575, 1.22364751], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [ ]:
ans= jacobian@dtheta
ans #v010

array([[ 0.03522729],
       [-0.46729636],
       [-0.61322338],
       [ 3.02972762],
       [ 0.3169054 ],
       [-3.05970097]])

In [ ]:
import numpy as np

theta = np.array([[1.00000000], [0.29000000], [0.04000000], [-0.34000000], [-0.66000000], [-0.49000000], [-0.37000000], [0.78000000]])
dtheta = np.array([[0.62000000], [0.12000000], [0.51000000], [0.73000000], [0.32000000], [-0.05000000], [-0.63000000], [0.98000000]])
jacobian = np.array([[0.13076572, 0.93232735, 0.00000000, 0.00000000, 0.93232735, 0.00000000,  0.00000000, 0.00000000], [0.93232735, -0.00000000, 0.00000000, 0.00000000, -0.00000000,  0.00000000, 1.00000000, 0.00000000], [0.33714396, -0.36161543, 0.00000000, 0.00000000, -0.36161543,  0.00000000, 0.00000000, 0.00000000], [-5.48980851, 0.90601652, 0.22171252, 0.22171252, 0.10486848, 0.00000000,  -2.00000000, 0.00000000], [0.93581935, 6.48532781, 0.78999223, 0.78999223, 3.14142383, 1.00000000,  -0.00000000, 1.00000000], [-0.45859107, 2.33591795, 0.57162561, 0.57162561, 0.27037493, 0.00000000,  -2.00000000, 0.00000000]])
T_1in0 = np.array([[0.78743547, -0.30428889, 0.53605377, -2.76911505], [0.13076572, 0.93232735, 0.33714396, -0.00927667], [-0.60236675, -0.19538165, 0.77393818, -2.85345886], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [ ]:
ans= jacobian@dtheta
ans #v010

array([[ 0.49129878],
       [-0.05195704],
       [ 0.04991847],
       [-1.72647786],
       [ 4.27329333],
       [ 2.05131942]])

In [ ]:
theta = np.array([[-0.10000000], [-0.02000000], [0.66000000], [-0.69000000], [-0.83000000], [-0.26000000], [0.59000000]])
dtheta = np.array([[-0.37000000], [-0.10000000], [0.73000000], [-0.94000000], [0.51000000], [0.19000000], [0.15000000]])
jacobian = np.array([[-1.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000], [0.00000000, -1.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000], [0.00000000, 0.00000000, -0.99500417, -0.09983342, -0.09983342,  -0.99500417, -0.09983342], [0.00000000, 0.00000000, -0.09983342, 0.99500417, 0.99500417,  -0.09983342, 0.99500417]])
T_1in0 = np.array([[-1.00000000, 0.00000000, 0.00000000, -9.98000000], [0.00000000, -0.99500417, -0.09983342, -8.26518991], [0.00000000, -0.09983342, 0.99500417, -1.76395457], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])


In [ ]:
ans= jacobian@dtheta
ans #v010

array([[ 0.37      ],
       [ 0.        ],
       [ 0.        ],
       [ 0.1       ],
       [-0.88745048],
       [-0.37044791]])

## 6.4

In [ ]:
from scipy.linalg import expm
import numpy as np

theta = np.array([[-0.43000000], [0.19000000], [0.06000000]])

s1 = np.array([[0],[0],[0],[0],[-1],[0]])
s2 = np.array([[0],[0],[0],[1],[0],[0]])
s3 = np.array([[0],[0],[1],[0],[-4],[0]])

M = [[-1,0,0,4],[0,-1,0,0],[0,0,1,6],[0,0,0,1]]

def twist(vector):
    vector=np.array(vector)
    return np.array([[0, -vector.item(2), vector.item(1),vector.item(3)],
                     [vector.item(2), 0, -vector.item(0),vector.item(4)],
                     [-vector.item(1), vector.item(0), 0,vector.item(5)],
                    [0,0,0,0]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])


    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

J1=s1;
J2=adjform(expm(twist(s1*theta.item(0))))@s2
J3=adjform((expm(twist(s1*theta.item(0))))@(scipy.linalg.expm(twist(s2*theta.item(1)))))@s3

print(repr(J1))
print(repr(J2))
print(repr(J3))


ans = np.array([[J1.item(0),J2.item(0),J3.item(0)],
                     [J1.item(1),J2.item(1),J3.item(1)],
                     [J1.item(2),J2.item(2),J3.item(2)],
                     [J1.item(3),J2.item(3),J3.item(3)],
                     [J1.item(4),J2.item(4),J3.item(4)],
                     [J1.item(5),J2.item(5),J3.item(5)]]);

print(repr(ans))

array([[ 0],
       [ 0],
       [ 0],
       [ 0],
       [-1],
       [ 0]])
array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])
array([[ 0.  ],
       [ 0.  ],
       [ 1.  ],
       [ 0.43],
       [-4.19],
       [ 0.  ]])
array([[ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.43],
       [-1.  ,  0.  , -4.19],
       [ 0.  ,  0.  ,  0.  ]])


In [ ]:
from scipy.linalg import expm
import numpy as np

theta = np.array([[-0.17000000], [-0.11000000], [0.48000000]])

s1 = np.array([[0],[0],[1],[0],[-2],[0]])
s2 = np.array([[0],[1],[0],[0],[0],[4]])
s3 = np.array([[-1],[0],[0],[0],[-2],[0]])

M = [[0,0,-1,0],[-1,0,0,0],[0,1,0,2],[0,0,0,1]]

def twist(vector):
    vector=np.array(vector)
    return np.array([[0, -vector.item(2), vector.item(1),vector.item(3)],
                     [vector.item(2), 0, -vector.item(0),vector.item(4)],
                     [-vector.item(1), vector.item(0), 0,vector.item(5)],
                    [0,0,0,0]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])


    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

J1=s1;
J2=adjform(expm(twist(s1*theta.item(0))))@s2
J3=adjform((expm(twist(s1*theta.item(0))))@(scipy.linalg.expm(twist(s2*theta.item(1)))))@s3

print(repr(J1))
print(repr(J2))
print(repr(J3))


ans = np.array([[J1.item(0),J2.item(0),J3.item(0)],
                     [J1.item(1),J2.item(1),J3.item(1)],
                     [J1.item(2),J2.item(2),J3.item(2)],
                     [J1.item(3),J2.item(3),J3.item(3)],
                     [J1.item(4),J2.item(4),J3.item(4)],
                     [J1.item(5),J2.item(5),J3.item(5)]]);

print(repr(ans))

array([[ 0],
       [ 0],
       [ 1],
       [ 0],
       [-2],
       [ 0]])
array([[0.16918235],
       [0.98558477],
       [0.        ],
       [0.        ],
       [0.        ],
       [3.97116953]])
array([[-0.97962799],
       [ 0.16815983],
       [-0.1097783 ],
       [-0.3012196 ],
       [-1.53522129],
       [ 0.33631966]])
array([[ 0.        ,  0.16918235, -0.97962799],
       [ 0.        ,  0.98558477,  0.16815983],
       [ 1.        ,  0.        , -0.1097783 ],
       [ 0.        ,  0.        , -0.3012196 ],
       [-2.        ,  0.        , -1.53522129],
       [ 0.        ,  3.97116953,  0.33631966]])


## 6.2

In [ ]:
# body twist v011
import numpy as np

theta = 0.36
dtheta = 0.56

T=np.array([[0,-1,0,-2],[0,0,1,2],[-1,0,0,0],[0,0,0,1]])

S=np.array([[0],
            [0],
            [-1],
            [-2],
            [0],
            [0]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])
    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

A=adjform(np.linalg.inv(T));
V=A@(S*dtheta) # when spatial v010 only s*dtheta
V

array([[0.56],
       [0.  ],
       [0.  ],
       [0.  ],
       [0.  ],
       [1.12]])

In [ ]:
theta = 0.41
dtheta = -0.72

T=np.array([[0,0,-1,0],[-1,0,0,2],[0,1,0,2],[0,0,0,1]])

S=np.array([[1],
            [0],
            [0],
            [0],
            [0],
            [-2]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])
    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

A=adjform(np.linalg.inv(T));
V=A@(S*dtheta) # when spatial v010 only s*dtheta
V


array([[ 0.  ],
       [ 0.  ],
       [ 0.72],
       [-1.44],
       [ 0.  ],
       [ 0.  ]])

In [ ]:
theta = 0.30
dtheta = 0.30

T=np.array([[0,-1,0,-2],[0,0,-1,-4],[1,0,0,0],[0,0,0,1]])

S=np.array([[0],
            [0],
            [0],
            [0],
            [0],
            [-1]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])
    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

A=adjform(np.linalg.inv(T));
V=A@(S*dtheta) # when spatial v010 only s*dtheta
V


array([[ 0. ],
       [ 0. ],
       [ 0. ],
       [-0.3],
       [ 0. ],
       [ 0. ]])