In [ ]:
import numpy as np


In [ ]:
theta = np.array([[0.47000000], [0.61000000], [0.56000000], [-0.28000000], [0.22000000], [-0.20000000], [-0.86000000], [0.23000000]])
endeffector_twist = np.array([[-1.94000000], [0.00000000], [0.00000000], [0.00000000], [0.46303756], [-6.96560226]])
jacobian = np.array([[0.00000000, 0.00000000, 0.00000000, -1.00000000, 0.00000000, 1.00000000,  0.00000000, 1.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [-0.30505864, -0.30505864, -0.30505864, 1.16672714, 0.99955003,  -1.29330815, -0.22797752, -0.00000000], [-0.95233357, -0.95233357, -0.95233357, -4.46682902, -0.02999550,  0.24872788, -0.97366640, 2.00000000]])
T_1in0 = np.array([[0.00000000, 0.30505864, 0.95233357, 0.83375819], [-1.00000000, 0.00000000, 0.00000000, -4.00000000], [0.00000000, -0.95233357, 0.30505864, -7.89799104], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
jac_inv = np.linalg.pinv(jacobian)
theta_dot = jac_inv @ endeffector_twist
theta_dot

array([[ 0.28903862],
       [ 0.28903862],
       [ 0.28903862],
       [ 0.89501084],
       [-0.39813634],
       [-0.10897079],
       [ 0.26164999],
       [-0.93601837]])

In [ ]:
import numpy as np

theta = np.array([[0.39000000], [0.30000000], [-0.08000000], [0.63000000], [0.53000000], [-0.72000000], [-0.43000000], [-0.64000000]])
jacobian = np.array([[0.10349353, 0.00000000, -0.93358404, 0.93358404, -0.32764604,  -0.59719544, -0.59719544, -0.00000000], [0.89281840, 0.00000000, -0.06482866, 0.06482866, -0.24394684,  0.80209576, 0.80209576, 0.00000000], [-0.43836558, 0.00000000, -0.35244585, 0.35244585, 0.91276394,  0.00000000, 0.00000000, 1.00000000], [3.67034948, 0.10349353, -1.41641816, 1.56790755, 1.38986629, 2.27293212,  1.60419152, 0.00000000], [2.13684707, 0.89281840, 9.44649077, -7.59532468, -1.86673538,  1.69229757, 1.19439088, -0.00000000], [5.21864377, -0.43836558, 2.01432943, -2.75610775, 0.00000000,  3.81793150, 2.00000000, 0.00000000]])
T_1in0 = np.array([[-0.67226377, 0.38760982, 0.63072977, 6.52238331], [0.73304195, 0.22942085, 0.64032458, -3.65237391], [0.10349353, 0.89281840, -0.43836558, -6.06198409], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
dtheta0 = np.array([[-1.41000000], [-2.68000000], [-0.46000000], [-0.91000000], [-0.82000000], [-1.30000000], [2.56000000], [0.14000000]])
N = np.identity(8)-(np.linalg.pinv(jacobian)@jacobian)
Ans = N @ dtheta0
Ans

array([[ 0.62415964],
       [-1.84286254],
       [ 0.24278042],
       [-0.04873094],
       [ 0.37952159],
       [-1.96757915],
       [ 1.41181031],
       [ 0.02993845]])

In [ ]:
import numpy as np

theta = np.array([[0.55000000], [0.20000000], [-0.52000000], [-0.60000000], [0.85000000], [-0.83000000], [0.46000000], [0.33000000]])
wrench_in_frame1 = np.array([[-2.47000000], [-0.05000000], [5.55000000], [0.17000000], [2.45000000], [7.51000000]])
jacobian = np.array([[0.00000000, 0.00000000, 0.00000000, -0.52268723, -0.52268723,  0.00000000, 0.00000000, 0.00000000], [-1.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.85252452, 0.85252452, 0.00000000,  0.00000000, 0.00000000], [0.00000000, 0.85252452, 0.00000000, 0.44331275, 0.44331275, 0.21091794,  0.21091794, -0.52268723], [0.00000000, 0.00000000, -1.00000000, -3.90504904, -3.90504904,  -0.96891242, -0.96891242, 0.00000000], [-2.00000000, 0.52268723, 0.00000000, 0.27179736, 0.27179736, 0.12931489,  0.12931489, 0.85252452]])
T_1in0 = np.array([[-0.52268723, -0.82602160, 0.21091794, 4.83836501], [0.00000000, -0.24740396, -0.96891242, 1.86811343], [0.85252452, -0.50643815, 0.12931489, 6.81924917], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
jac_tra = jacobian.transpose()
ans = jac_tra @ wrench_in_frame1
ans

array([[-14.97      ],
       [  4.07031027],
       [ -2.45      ],
       [ -1.42826026],
       [ -1.42826026],
       [ -1.36682456],
       [ -1.36682456],
       [  6.31360232]])

In [ ]:
import numpy as np

theta = np.array([[-0.62000000], [-0.55000000], [-0.14000000], [-0.17000000], [0.68000000], [-0.89000000], [-0.64000000], [-0.48000000]])
wrench_in_frame1 = np.array([[9.46000000], [-5.35000000], [4.98000000], [1.32000000], [-9.06000000], [9.95000000]])
jacobian = np.array([[0.00000000, 0.44944772, 0.00000000, 0.46139495, 0.46139495, -0.88699492,  -0.88699492, -0.00000000], [0.00000000, 0.87201834, 0.00000000, -0.04078501, -0.04078501,  0.00000000, 0.00000000, 1.00000000], [0.00000000, -0.19385760, 0.00000000, 0.88625689, 0.88625689, 0.46177918,  0.46177918, 0.00000000], [0.79316744, 5.36229394, 0.44944772, -4.60488324, -4.60488324,  -2.40512282, -0.92355835, 0.00000000], [-0.28972192, -2.29057220, 0.87201834, -2.22415799, -2.22415799,  -1.46522341, 0.92355835, 0.00000000], [0.53567398, 2.12862346, -0.19385760, 2.29499773, 2.29499773,  -4.61980930, -1.77398985, -2.00000000]])
T_1in0 = np.array([[-0.79316744, 0.28972192, -0.53567398, -2.73786881], [-0.44944772, -0.87201834, 0.19385760, -3.26296353], [-0.41095274, 0.39451898, 0.82187141, 0.05707417], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
jac_tra = jacobian.transpose()
ans = jac_tra @ wrench_in_frame1
ans

array([[  9.00181772],
       [ 47.63168202],
       [ -9.23609829],
       [ 45.90420827],
       [ 45.90420827],
       [-41.95825219],
       [-33.32904631],
       [-25.25      ]])

In [ ]:
import numpy as np

T_F1_in_S = np.array([[0.00109391, -0.15323490, -0.98818919, 0.14630942], [0.73718587, -0.66758592, 0.10433617, 2.70270363], [-0.67568913, -0.72859324, 0.11223233, 1.61735658], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_F2_in_S = np.array([[-0.55851054, 0.79755805, 0.22796301, 0.25195462], [0.17962419, -0.15201355, 0.97191925, 2.73317526], [0.80981549, 0.58377482, -0.05835955, 1.61280788], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_com_in_S = np.array([[0.19772730], [2.71892576], [1.60482453]])
W1_in_F1 = np.array([[-0.23368287], [0.24177716], [0.12260615], [0.20625364], [-0.18678061], [0.02919171]])
W2_in_F2 = np.array([[-0.03007632], [0.08486623], [0.34898551], [0.04659247], [-0.03943059], [0.25210480]])
gravity_constant = 9.81000000

F1 = W1_in_F1[3:6]
F2 = W2_in_F2[3:6]
(np.linalg.norm(F1)+np.linalg.norm(F2))/gravity_constant

0.054961646502401706