In [ ]:
import numpy as np
import scipy.linalg as sc
def skew(vector):
  

    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
def unskew(matrix):
  
      return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
def skewtomatrix(vector):
      [a,b] = np.split(vector,2)
      a=skew(a)
      a=np.concatenate((a,b), axis=1)
      a = np.concatenate((a, np.array([[0,0,0,0]])), axis=0);
      return a
def matrixtoskew(matrix):
  return np.array([[matrix[2, 1]], 
                    [matrix[0, 2]], 
                    [matrix[1, 0]],
                    [matrix[0, 3]],
                    [matrix[1, 3]],
                    [matrix[2, 3]]])
def toadjoint(matrix):
    r = matrix[:3,:3]
    p = matrix[0:3,3]
    A_u = np.concatenate((r,np.zeros((3,3),int)), axis=1)
    A_d = np.concatenate(((skew(p) @ r),r), axis=1)
    a=np.concatenate((A_u,A_d), axis=0)
    return a


2

In [ ]:
import numpy as np

V = np.array([[  8], [  1], [  6], [ -5], [ -3], [-10]])

skewtomatrix(V)

array([[  0,  -6,   1,  -5],
       [  6,   0,  -8,  -3],
       [ -1,   8,   0, -10],
       [  0,   0,   0,   0]])

3

In [ ]:
import numpy as np

M = np.array([[-0.00728336, 0.55300612, -0.83314535, 1.06133247], [0.94552848, -0.26735957, -0.18572762, 0.99720340], [-0.32545790, -0.78911538, -0.52093576, 1.78437880], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
V_s = np.array([[-0.70900165], [-0.27580585], [-0.34436181], [0.82998398], [-0.24843366], [-0.68000909]])

sc.expm(skewtomatrix(V_s)) @ M

array([[ 0.41185636,  0.49820029, -0.76300118,  1.94682309],
       [ 0.45061677, -0.8391204 , -0.30466616,  1.11146697],
       [-0.79203463, -0.21834244, -0.57009448,  0.69959686],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

4

In [ ]:
import numpy as np

T_1in0 = np.array([[0.19566184, -0.77703485, -0.59827527, -0.51952598], [0.56269453, 0.58860391, -0.58044836, 0.18933074], [0.80317576, -0.22307463, 0.55240059, 0.74587062], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
-matrixtoskew(sc.logm(sc.inv(T_1in0)))

array([[ 0.25408358],
       [-0.99639584],
       [ 0.95251332],
       [ 0.0387514 ],
       [ 0.46597475],
       [ 0.88633881]])

5

In [ ]:
import numpy as np

t = 1.54377369
T_1in0 = np.array([[-0.93473440, 0.00735920, 0.35527094, 0.68463401], [-0.35527511, -0.03948572, -0.93392744, 0.58508502], [0.00715517, -0.99919303, 0.03952321, 0.28263635], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_2in0 = np.array([0.86434401, 1.08743525, -0.39592642])
R_2in0 = np.array([[-0.82256936, 0.48417399, 0.29825357], [-0.52867234, -0.84431138, -0.08742915], [0.20948797, -0.22959495, 0.95047407]])

T10=sc.inv(T_1in0)
p02 = p_2in0.reshape(3,1)
T02 = np.concatenate((R_2in0,p02), axis=1)
T02 = np.concatenate((T02, np.array([[0,0,0,1]])), axis=0)
matrixtoskew(sc.logm(T10 @ T02))/t

array([[ 0.84680479],
       [-0.20135064],
       [-0.01797826],
       [-0.28914174],
       [ 0.18603661],
       [-0.47931594]])

In [ ]:
6

In [ ]:
import numpy as np

T = np.array([[-0.30163571, 0.92170405, 0.24388016, 0.93348172], [-0.87250629, -0.36997821, 0.31913775, 0.90522137], [0.38438090, -0.11652363, 0.91579122, 0.58455898], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
toadjoint(T)


array([[-0.30163571,  0.92170405,  0.24388016,  0.        ,  0.        ,
         0.        ],
       [-0.87250629, -0.36997821,  0.31913775,  0.        ,  0.        ,
         0.        ],
       [ 0.3843809 , -0.11652363,  0.91579122,  0.        ,  0.        ,
         0.        ],
       [ 0.85798119,  0.11079441,  0.64243895, -0.30163571,  0.92170405,
         0.24388016],
       [-0.53513641,  0.64756306, -0.71231203, -0.87250629, -0.36997821,
         0.31913775],
       [-0.54142158, -1.1797141 ,  0.07714372,  0.3843809 , -0.11652363,
         0.91579122]])

7

In [ ]:
import numpy as np

V_sb_in_b = np.array([[-0.93477106], [-0.85832345], [-0.86945878], [-0.64580688], [0.91756792], [0.64423437]])
T_sb = np.array([[-0.78510668, -0.37298356, -0.49446007, -0.25423134], [0.16986062, 0.63806430, -0.75101353, -0.87164444], [0.59561302, -0.67361503, -0.43759333, 0.13134053], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

toadjoint(T_sb) @ V_sb_in_b

array([[ 1.48394819],
       [-0.05347104],
       [ 0.40188713],
       [-0.49703839],
       [ 0.28901629],
       [ 0.02241801]])

8

In [ ]:
import numpy as np

T_sb = np.array([[-0.22052091, -0.89410570, 0.38980189, -0.99112670], [-0.15643243, -0.36204669, -0.91894020, 0.59559856], [0.96275616, -0.26362319, -0.06002826, -0.87501666], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
V_sb_in_s = np.array([[0.00423026], [-0.70567809], [-0.37807766], [-0.62703912], [0.25526076], [1.55641895]])
q_B = np.array([[-0.82814003], [-1.02377835], [1.19515181], [1.00000000]])
T = np.linalg.inv(T_sb)
vb = toadjoint(T) @ V_sb_in_s


In [ ]:
[a,b] = np.split(vb,2)
ans = b + skew(a) @ q_B[0:3]
ans = np.concatenate((ans, np.array([[0]])), axis=0);
ans

array([[ 1.78959846e+00],
       [-9.01780973e-01],
       [ 1.71571836e-03],
       [ 0.00000000e+00]])

dont forget to add 0 at end of matrix