In [ ]:
import numpy as np
import scipy.linalg as sc
def skew(vector):
  

    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
def unskew(matrix):
  
      return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
def skewtomatrix(vector):
      [a,b] = np.split(vector,2)
      a=skew(a)
      a=np.concatenate((a,b), axis=1)
      a = np.concatenate((a, np.array([[0,0,0,0]])), axis=0);
      return a
def matrixtoskew(matrix):
  return np.array([[matrix[2, 1]], 
                    [matrix[0, 2]], 
                    [matrix[1, 0]],
                    [matrix[0, 3]],
                    [matrix[1, 3]],
                    [matrix[2, 3]]])
def toadjoint(matrix):
    r = matrix[:3,:3]
    p = matrix[0:3,3]
    A_u = np.concatenate((r,np.zeros((3,3),int)), axis=1)
    A_d = np.concatenate(((skew(p) @ r),r), axis=1)
    a=np.concatenate((A_u,A_d), axis=0)
    return a


In [ ]:
a = np.array([[1],[0],[0]])
b = np.array([[4],[0],[0]])
-skew(a) @ b


array([[0],
       [0],
       [0]])

[[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]]

       [[0], [0], [1], [-2], [0], [0]]

In [ ]:
## Homework 5.1 Revolute 
import numpy as np
import scipy.linalg as sc
theta = 0.36
def skew(vector):
    """
    this function returns a numpy array with the skew symmetric cross product matrix for vector.
    the skew symmetric cross product matrix is defined such that
    np.cross(a, b) = np.dot(skew(a), b)

    :param vector: An array like vector to create the skew symmetric cross product matrix for
    :return: A numpy array of the skew symmetric cross product vector
    """

    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])

def unskew(matrix):
    """
    this functions returns a numpy array which is an unskewed form of a matrix.
    
    :param matrix: A skew symmetric cross product matrix of a vector
    return: the numpy array whose skew symmetric cross product matrix is the parameter of the function
    """
    
    return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
M = np.array([[ 0,  -1,  0, -2],
              [ 0,   0,  1, -4],
              [-1,   0,  0,  0],
              [ 0,   0,  0,  1]])    #for axes rotation, look for frame 1
w = np.array([[-1],[0],[0]])         ##Look at frame 0
p = np.array([[0],[-4],[0]])         ##Position of joint wrt frame 0
wskw = skew(w)
v = -wskw*p
v=unskew(v)
s = np.hstack((wskw,v))
print(s)
zero = np.zeros((1,4))
S = np.vstack((s,zero))
T = sc.expm(theta*S)@M
T

In [ ]:
M = np.array([[ 0,  1,  0, 2],
              [ 0,  0,  1, 0],
              [ 1,  0,  0, 0],
              [ 0,  0,  0, 1]]) 

In [ ]:
a = np.array([[0],[1],[0]])
b = np.array([[2],[0],[-2]])
v= -skew(a) @ b
theta = 0.5

In [ ]:
s = np.hstack((skew(a),v))
s = np.concatenate((s, np.array([[0,0,0,0]])), axis=0);
T = sc.expm(theta*s)@M
T

array([[ 0.47942554,  0.87758256,  0.        ,  2.95885108],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.87758256, -0.47942554,  0.        , -0.24483488],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
M = np.array([[ 0,  1,  0, 4],
              [ 0,  0,  -1, 0],
              [ -1,  0,  0, 0],
              [ 0,  0,  0, 1]]) 
M

array([[ 0,  1,  0,  4],
       [ 0,  0, -1,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1]])

In [ ]:
a = np.array([[0],[1],[0]])
b = np.array([[2],[0],[0]])
v= -skew(a) @ b
theta = 0.24

In [ ]:
s = np.hstack((skew(a),v))
s = np.concatenate((s, np.array([[0,0,0,0]])), axis=0);
T = sc.expm(theta*s)@M
T

array([[-0.23770263,  0.97133797,  0.        ,  3.94267595],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [-0.97133797, -0.23770263,  0.        , -0.47540525],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
M = np.array([[ 0,  0,  1, 2],
              [ 0,  1,  0, 0],
              [ -1,  0,  0, -2],
              [ 0,  0,  0, 1]]) 
M

array([[ 0,  0,  1,  2],
       [ 0,  1,  0,  0],
       [-1,  0,  0, -2],
       [ 0,  0,  0,  1]])

In [ ]:
a = np.array([[0],[1],[0]])
b = np.array([[2],[0],[0]])
s = np.array([[ 0,  0,  0, 1],
                     [ 0,  0,  0, 0],
                      [ 0,  0,  0, 0],
                       [ 0,  0,  0, 0]]) 
theta = -0.64
sc.expm(theta*s)@M

array([[ 0.  ,  0.  ,  1.  ,  1.36],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [-1.  ,  0.  ,  0.  , -2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [ ]:
## Prismatic
## Homework 5.1 Revolute 
import numpy as np
import scipy.linalg as sc
def skew(vector):
  
    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])

def unskew(matrix):
    """
    this functions returns a numpy array which is an unskewed form of a matrix.
    
    :param matrix: A skew symmetric cross product matrix of a vector
    return: the numpy array whose skew symmetric cross product matrix is the parameter of the function
    """
    
    return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
M = np.array([[ 0,  0,  1, 2],
              [ 0,  1,  0, 0],
              [ -1,  0,  0, -2],
              [ 0,  0,  0, 1]])     #for axes rotation, look for frame 1
theta = -0.64
sskew = np.array([[ 0.  ,  0.  ,  0.  ,  0.  ],
                  [ 0.  ,  0.  ,  0.  ,  1  ],
                  [ 0.  ,  0.  ,  0.  ,    0 ],
                  [ 0.  ,  0.  ,  0.  ,   0  ]])
                 
exp = theta*sskew
T = sc.expm(exp)@M
T

array([[ 0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , -0.64],
       [-1.  ,  0.  ,  0.  , -2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [ ]:
M = np.array([[ 0,  1,  0, -2],
              [ 0,  0,  1, 2],
              [ 1,  0,  0, 0],
              [ 0,  0,  0, 1]])     #for axes rotation, look for frame 1
theta = -0.75
sskew = np.array([[ 0.  ,  0.  ,  0.  ,  0.  ],
                  [ 0.  ,  0.  ,  0.  ,  0 ],
                  [ 0.  ,  0.  ,  0.  ,    -1 ],
                  [ 0.  ,  0.  ,  0.  ,   0  ]])
                 
exp = theta*sskew
T = sc.expm(exp)@M
T



array([[ 0.  ,  1.  ,  0.  , -2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.75],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [ ]:
M = np.array([[ 1,  0,  0, 0],
              [ 0,  1,  0, 0],
              [ 0,  0,  1, 4],
              [ 0,  0,  0, 1]]) 
M

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 4],
       [0, 0, 0, 1]])

In [ ]:
a = np.array([[0],[0],[1]])
b = np.array([[0],[0],[2]])
v= -skew(a) @ b
theta = -0.12

In [ ]:
s = np.hstack((skew(a),v))
s = np.concatenate((s, np.array([[0,0,0,0]])), axis=0);
T = sc.expm(theta*s)@M
T

array([[ 0.99280864,  0.11971221,  0.        ,  0.        ],
       [-0.11971221,  0.99280864,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  4.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
a = np.array([[-1],[0],[0]])
b = np.array([[-4],[0],[6]])
v= -skew(a) @ b
v

array([[ 0],
       [-6],
       [ 0]])

In [ ]:
a1 = np.array([[0],[0],[1],[0],[0],[0]])
a1

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [ ]:
a2 = np.array([[0],[0],[1],[0],[2],[0]])
a2

array([[0],
       [0],
       [1],
       [0],
       [2],
       [0]])

In [ ]:
a3 = np.array([[-1],[0],[0],[0],[-6],[0]])

In [ ]:
a4 = np.array([[0],[0],[1],[0],[2],[0]])

In [ ]:
a = np.concatenate((a1,a2,a3,a4), axis=1);
a

array([[ 0,  0, -1,  0],
       [ 0,  0,  0,  0],
       [ 1,  1,  0,  1],
       [ 0,  0,  0,  0],
       [ 0,  2, -6,  2],
       [ 0,  0,  0,  0]])

[[ 0,  1,  0,  4],
 [ 0,  0, 1,  0],
 [1,  0,  0,  8],
 [ 0,  0,  0,  1]]

In [ ]:
a = np.array([[0],[0],[1]])
b = np.array([[0],[-4],[0]])
v= -skew(a) @ b
v

array([[-4],
       [ 0],
       [ 0]])

In [ ]:
a1 = np.array([[0],[0],[1],[-4],[0],[0]])

In [ ]:
a2 = np.array([[0],[0],[0],[ 0],[-1],[ 0]])

In [ ]:
a3 = np.array([[0],[0],[0],[0],[0],[1]])

In [ ]:
a4 = np.array([[0],[1],[0],[ 2],[ 0],[-2]])

In [ ]:
a = np.concatenate((a1,a2,a3,), axis=1);
a

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 1,  0,  0],
       [-4,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [ ]:
[[ 0.  ,  0.  ,  1.  , -2.  ],
 [ 0.  ,  1.  ,  0.  ,  -6.  ],
 [ -1.  ,  0.  ,  0.  ,  0],
 [ 0.  ,  0.  ,  0.  ,  1.  ]]

In [ ]:
a = np.array([[1],[0],[0]])
b = np.array([[2],[4],[0]])
v= -skew(a) @ b
v

array([[ 0],
       [ 0],
       [-4]])

In [ ]:
a1 = np.array([[0],[0],[0],[0],[0],[1]])

In [ ]:
a2 = np.array([[0],[0],[1],[2],[-2],[0]])

In [ ]:
a3 = np.array([[1],[0],[0],[0],[0],[-4]])

In [ ]:
a1m = screwtomatrix(a1)
a1m

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [ ]:
a2m = screwtomatrix(a2)

In [ ]:
a3m = screwtomatrix(a3)

In [ ]:
M= np.array([[0, -1, 0, 2],
            [1, 0, 0, 6],
            [0, 0, 1, 0],
            [0, 0, 0, 1]])


In [ ]:
import numpy as np

theta = np.array([[0.21, 0.11, -0.77]])
T1 = theta[0][0]
T2 = theta[0][1]
T3 = theta[0][2]


0.21

In [ ]:
st1 = sc.expm(a1m*T1)
st2 = sc.expm(a2m*T2)
st3 = sc.expm(a3m*T3)

In [ ]:
a = np.matmul(st1, st2)
b = np.matmul(a, st3)
c = np.matmul(b, M)
c

array([[-0.07881101, -0.9939561 , -0.07642054,  1.62282137],
       [ 0.71357169, -0.1097783 ,  0.69192787,  5.41505557],
       [-0.69613524,  0.        ,  0.71791067, -1.18227048],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
a = np.array([[0],[0],[0]])
b = np.array([[2],[4],[0]])
v= -skew(a) @ b
v

In [ ]:
M= np.array([[-1, 0, 0, -8],
            [0, -1, 0, 0],
            [0, 0, 1, -2],
            [0, 0, 0, 1]])

In [ ]:
a1 = np.array([[0],[0],[0],[0],[0],[-1]])

In [ ]:
a2 = np.array([[0],[0],[0],[0],[1],[0]])

In [ ]:
a3 = np.array([[0],[0],[0],[-1],[0],[0]])

In [ ]:
a1m = skewtomatrix(a1)
a2m = skewtomatrix(a2)
a3m = skewtomatrix(a3)


In [ ]:

theta = np.array([[0.11, -0.28, 0.50]])
T1 = theta[0][0]
T2 = theta[0][1]
T3 = theta[0][2]


In [ ]:
st1 = sc.expm(a1m*T1)
st2 = sc.expm(a2m*T2)
st3 = sc.expm(a3m*T3)

In [ ]:
a = np.matmul(st1, st2)
b = np.matmul(a, st3)
c = np.matmul(b, M)
c

array([[-1.  ,  0.  ,  0.  , -8.5 ],
       [ 0.  , -1.  ,  0.  , -0.28],
       [ 0.  ,  0.  ,  1.  , -2.11],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [ ]:
M= np.array([[0, 1, 0, -2],
            [-1, 0, 0, 0],
            [0, 0, 1, 8],
            [0, 0, 0, 1]])


In [ ]:
a = np.array([[0],[0],[1]])
b = np.array([[-2],[0],[4]])
v= -skew(a) @ b
v

array([[0],
       [2],
       [0]])

In [ ]:
a1 = np.array([[0],[1],[0],[-2],[0],[-2]])

In [ ]:
a2 = np.array([[0],[0],[1],[0],[2],[0]])

In [ ]:
a3 = np.array([[0],[0],[0],[0],[1],[0]])

In [ ]:
a1m = skewtomatrix(a1)
a2m = skewtomatrix(a2)
a3m = skewtomatrix(a3)

In [ ]:
theta = np.array([[-0.82, 0.27, -0.13]])
T1 = theta[0][0]
T2 = theta[0][1]
T3 = theta[0][2]

In [ ]:
st1 = sc.expm(a1m*T1)
st2 = sc.expm(a2m*T2)
st3 = sc.expm(a3m*T3)

In [ ]:
a = np.matmul(st1, st2)
b = np.matmul(a, st3)
c = np.matmul(b, M)
c

array([[ 0.18196984,  0.65750494, -0.73114583, -6.3632189 ],
       [-0.9637709 ,  0.26673144,  0.        , -0.12529022],
       [ 0.19501958,  0.70465707,  0.68222121,  6.11867979],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
M= np.array([[0, -1, 0, 0],
            [0, 0, -1, -4],
            [-1, 0, 0, -2],
            [0, 0, 0, 1]])

In [ ]:
a = np.array([[0],[0],[-1]])
b = np.array([[0],[2],[2]])
v= -skew(a) @ b
v

array([[-2],
       [ 0],
       [ 0]])

In [ ]:
a1 = np.array([[0],[0],[1],[-2],[0],[0]])
a2 = np.array([[0],[0],[1],[ 0],[0],[ 0]])
a3 = np.array([[0],[0],[-1],[ -2],[ 0],[0]])

In [ ]:
a = np.concatenate((a1,a2,a3,), axis=1);
a

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 1,  1, -1],
       [-2,  0, -2],
       [ 0,  0,  0],
       [ 0,  0,  0]])