In [ ]:

import numpy as np


Q(a)=R(ab)q(b)+p(b)      

P(a) = T(ab).P(b) if v put 0 instead of 1


In [ ]:
p_7 = np.array([[-0.29509367], [-0.41406722]])
R_67 = np.array([[0.89350983, -0.44904362], [0.44904362, 0.89350983]])
q_6 = np.array([[-0.14793751], [0.70972393]])
np.transpose(R_67) @ (q_6 - p_)

array([[0.63611672],
       [0.9380389 ]])

In [ ]:
import numpy as np

R1 = np.array([[-0.80770660, -0.35940187, -0.46737603], [0.18817389, -0.90840642, 0.37334750], [-0.55874917, 0.21360727, 0.80135591]])
R2 = np.array([[0.08837444, 0.07235987, 1.08521507], [0.90022846, -0.60682110, 0.03385578], [0.71182643, 0.71472442, -0.14385736]])
R3 = np.array([[-0.80424095, -0.61520797, 0.00152190], [-0.23712715, 0.25283222, -1.15212708], [0.59944272, -0.64670562, -0.33329938]])
R4 = np.array([[0.61730009, 0.09405591, -0.58532303], [-0.56085986, -0.59787641, -0.54073394], [-0.49262443, 0.66841786, -0.34374208]])
R5 = np.array([[-0.21268736, -0.50479768, 0.59596264], [-0.61138387, 0.66913509, 0.28343053], [-0.85195315, -0.30775558, -0.74628417]])

In [ ]:
np.transpose(R5) @ R5

array([[ 1.14485032, -0.03954098,  0.33576057],
       [-0.03954098,  0.79727596,  0.11848587],
       [ 0.33576057,  0.11848587,  0.9924444 ]])

In [ ]:
import numpy as np

T54 = np.array([[-0.15481738, 0.33226861, -0.93039193, 0.91462338], [-0.78935123, -0.60792288, -0.08575785, 0.24291061], [-0.59410119, 0.72112921, 0.35639366, -0.17273612], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_5 = np.array([[-0.31161921], [0.02300291], [0.57511853], [1]])

T= np.linalg.inv(T54)
T@p_5

array([[-0.08087327],
       [ 0.26554483],
       [ 1.42627569],
       [ 1.        ]])

In [ ]:
import numpy as np

T_45 = np.array([[0.40578491, -0.85515674, -0.32256093, 0.69286662], [0.42519458, -0.13577553, 0.89486009, 0.25811208], [-0.80904152, -0.50027188, 0.30851235, -0.97798011], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
v_4 = np.array([[-0.67610229], [0.28056531], [-0.02583979], [0]])

T= np.linalg.inv(T_45)
T@v_4

array([[-0.1341518 ],
       [ 0.55300645],
       [ 0.46117899],
       [ 0.        ]])