Question 1

In [ ]:

import numpy as np
import scipy # this library handles the big rotations matrix of alpha, beta, and gama

theta1 = 1.91
theta2 = 0.02
theta3 = 0.82

from scipy.spatial.transform import Rotation as R


r = R.from_euler('XYZ', [[theta1, theta2, theta3]], degrees=False) # have to spasify the sequence (XYZ, XYX, etc)
matrix = r.as_matrix()
matrix

array([[[ 0.68208477, -0.73099961,  0.01999867],
        [-0.23041261, -0.24078851, -0.94283133],
        [ 0.69402478,  0.63848295, -0.3326697 ]]])

In [ ]:
def rot2eul(R):
    beta = -np.arcsin(R[2,0])
    alpha = np.arctan2(R[2,1]/np.cos(beta),R[2,2]/np.cos(beta))
    gamma = np.arctan2(R[1,0]/np.cos(beta),R[0,0]/np.cos(beta))
    return np.array((alpha, beta, gamma))


2

In [ ]:
import numpy as np

R=R_1in0 = np.array([[0.375012871259, 0.753567992980, -0.539907979516], [-0.258635256838, -0.474235487723, -0.841551249838], [-0.890209610322, 0.455231789465, 0.017054839505]])

ang = rot2eul(R)

print (ang)

[ 1.53334976  1.09780509 -0.60375962]


In [ ]:
import numpy as np

p_2in5 = np.array([[-0.85029087], [-0.06938259], [0.83669099]])
R_2in5 = np.array([[-0.25863648, 0.32969519, 0.90796930], [-0.52401991, 0.74173796, -0.41860237], [-0.81148648, -0.58405983, -0.01907365]])

R25= np.transpose(R_2in5)
-R25 @ p_2in5


array([[0.42268933],
       [0.82047811],
       [0.75895304]])