In [ ]:
import numpy as np
import scipy.linalg as sc
def skew(vector):
  

    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
def unskew(matrix):
  
      return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
def skewtomatrix(vector):
      [a,b] = np.split(vector,2)
      a=skew(a)
      a=np.concatenate((a,b), axis=1)
      a = np.concatenate((a, np.array([[0,0,0,0]])), axis=0);
      return a
def matrixtoskew(matrix):
  return np.array([[matrix[2, 1]], 
                    [matrix[0, 2]], 
                    [matrix[1, 0]],
                    [matrix[0, 3]],
                    [matrix[1, 3]],
                    [matrix[2, 3]]])

In [ ]:
import numpy as np

R = np.array([[0.30662148, -0.36806660, 0.87778713], [-0.54589300, 0.68746522, 0.47894927], [-0.77973335, -0.62603398, 0.00986663]])
w = np.array([[-0.50850899], [0.98563000], [-0.82055478]])

np.transpose(skew(-w) @ np.transpose(R))

array([[-0.56315452, -0.19476293,  0.11505015],
       [-1.03616964, -0.69148512, -0.18846627],
       [ 0.50397033, -0.6448312 , -1.08687249]])

In [ ]:
R @ skew(w)

array([[-0.56315452, -0.19476293,  0.11505015],
       [-1.03616964, -0.69148512, -0.18846627],
       [ 0.50397033, -0.6448312 , -1.08687249]])

2

In [ ]:
import numpy as np

w_01in0 = np.array([[0.35411453], [0.32983183], [0.09414417]])
w_01in1 = np.array([[0.36302153], [0.26490978], [-0.20270037]])

skew(w_01in1)

array([[ 0.        ,  0.20270037,  0.26490978],
       [-0.20270037,  0.        , -0.36302153],
       [-0.26490978,  0.36302153,  0.        ]])

3

In [ ]:
import numpy as np

w01 = np.array([[2.90], [-1.03], [1.65]])
t = 3.26

sc.expm(skew(w01)*t)

array([[ 0.80711931,  0.28511181,  0.51698131],
       [-0.58967099,  0.43245646,  0.68210669],
       [-0.02909523, -0.85539036,  0.51716612]])

4

In [ ]:
import numpy as np

R01 = np.array([[-0.56926025, 0.37281476, -0.73277003], [0.14482931, 0.92281193, 0.35699104], [0.80930046, 0.09709423, -0.57931466]])
w1 = np.array([[0.77207698], [-0.65361054], [0.92188148]])

-R01 @ w1



array([[ 1.35871551],
       [ 0.1622368 ],
       [-0.02732099]])

In [ ]:
R01 @ w1

array([[0.38192437],
       [0.25589447],
       [0.18956703]])

5

In [ ]:
import numpy as np

R = np.array([[0.70574779, -0.46667704, -0.53304089], [0.53035539, 0.84686683, -0.03923931], [0.46972674, -0.25500805, 0.84517908]])
theta = np.arccos(.5*(np.trace(R)-1))
w = (R - np.transpose(R)) / (2 * np.sin(theta))
print(theta)
unskew(w)

0.7969423820877283


array([[-0.1508403 ],
       [-0.70101798],
       [ 0.6970086 ]])

6

for frame 1

In [ ]:
import numpy as np

R_1in0 = np.array([[0.96212692, -0.07475503, 0.26215161], [-0.26663214, -0.45821666, 0.84790612], [0.05673699, -0.88569135, -0.46079468]])
R_2in0 = np.array([[0.80545878, -0.34235092, 0.48376855], [-0.57982486, -0.28630192, 0.76278067], [-0.12263480, -0.89488941, -0.42910796]])

R= np.transpose(R_1in0) @ R_2in0
theta = np.arccos(.5*(np.trace(R)-1))
w = (R - np.transpose(R)) / (2 * np.sin(theta))
print(theta)
unskew(w)


0.3984977335136365


array([[-0.11014624],
       [-0.59491386],
       [-0.79620679]])

frame 2 and for 0 R01 @ R02T

In [ ]:
import numpy as np

R_1in0 = np.array([[0.96212692, -0.07475503, 0.26215161], [-0.26663214, -0.45821666, 0.84790612], [0.05673699, -0.88569135, -0.46079468]])
R_2in0 = np.array([[0.80545878, -0.34235092, 0.48376855], [-0.57982486, -0.28630192, 0.76278067], [-0.12263480, -0.89488941, -0.42910796]])

R= np.transpose(R_2in0) @ R_1in0
theta = np.arccos(.5*(np.trace(R)-1))
w = (R - np.transpose(R)) / (2 * np.sin(theta))
print(theta)
unskew(w)

7

In [ ]:
"""
VARIANT
GIVEN - R01, w1, t, p1
ASKED - p1, v1, 
"""
import numpy as np

R01 = np.array([[-0.880723783899, 0.465271346852, -0.088590012267], [0.374153764675, 0.568781021040, -0.732459630617], [-0.290404161221, -0.678240904033, -0.675021999080]])
w1 = np.array([[0.230000000000], [2.400000000000], [-1.740000000000]])
t = 3.430000000000
p1 = np.array([[0.260000000000], [-2.690000000000], [0.000000000000]])

p1
skew(w1) @ p1


array([[-4.6806],
       [-0.4524],
       [-1.2427]])

In [ ]:
"""
VARIANT
GIVEN - R01, w1, t, p1
ASKED - p0, w0, 
"""
import numpy as np

R01 = np.array([[0.233998425649, 0.825081972256, -0.514280541973], [-0.349582059854, -0.422186328623, -0.836391706889], [-0.907213932996, 0.375497593844, 0.189642919181]])
w1 = np.array([[-2.000000000000], [-0.200000000000], [-2.860000000000]])
t = 9.390000000000
p1 = np.array([[0.460000000000], [1.950000000000], [1.380000000000]])

R = R01 @ sc.expm(skew(w1)*t)

p0 = R @ p1
w0 = R01 @ w1
v0=skew(w0) @ p0

array([[-4.00607141],
       [ 2.78037193],
       [-4.57260103]])

In [ ]:
"""
VARIANT
GIVEN - R01, w0, t, p1
ASKED - p1, v1, 
"""

import numpy as np

R01 = np.array([[0.292127321279, 0.921969847908, -0.254230658478], [0.951444134518, -0.307134389572, -0.020555428324], [-0.097034463227, -0.235881466609, -0.966925150493]])
w0 = np.array([[-1.640000000000], [3.000000000000], [-3.060000000000]])
t = 3.270000000000
p1 = np.array([[3.080000000000], [-1.940000000000], [-2.420000000000]])

w1 = np.transpose(R01) @ w0

v1=skew(w1) @ p1


array([[10.5714423 ],
       [16.67396301],
       [ 0.08783224]])

In [ ]:
"""
VARIANT
GIVEN - R01, w0, t, p1
ASKED - p0, v0, 
"""
import numpy as np

R01 = np.array([[-0.618574132187, 0.169988165799, -0.767118026433], [0.203897665328, 0.977598806186, 0.052214138092], [0.758809452408, -0.124115259463, -0.639377523303]])
w0 = np.array([[0.040000000000], [-1.140000000000], [2.640000000000]])
t = 11.360000000000
p1 = np.array([[0.710000000000], [-0.960000000000], [-2.100000000000]])

w1 = np.transpose(R01) @ w0
R = R01 @ sc.expm(skew(w1)*t)
p0 =R @ p1
v0=skew(w0) @ p0

array([[-2.64008296],
       [ 0.88002862],
       [ 0.42001362]])