In [ ]:
import numpy as np
import scipy.linalg as sc
def skew(vector):
  

    vector = np.array(vector)

    return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
def unskew(matrix):
  
      return np.array([[matrix[2, 1]], 
                     [matrix[0, 2]], 
                     [matrix[1, 0]]])
def skewtomatrix(vector):
      [a,b] = np.split(vector,2)
      a=skew(a)
      a=np.concatenate((a,b), axis=1)
      a = np.concatenate((a, np.array([[0,0,0,0]])), axis=0);
      return a
def matrixtoskew(matrix):
  return np.array([[matrix[2, 1]], 
                    [matrix[0, 2]], 
                    [matrix[1, 0]],
                    [matrix[0, 3]],
                    [matrix[1, 3]],
                    [matrix[2, 3]]])

def toadjoint(matrix):
    r = matrix[:3,:3]
    p = matrix[0:3,3]
    A_u = np.concatenate((r,np.zeros((3,3),int)), axis=1)
    A_d = np.concatenate(((skew(p) @ r),r), axis=1)
    a=np.concatenate((A_u,A_d), axis=0)
    return a 

In [ ]:
a= np.array([[0],[0],[-1]])
b= np.array([[2],[-4],[0]])
-skew(a) @ b

array([[4],
       [2],
       [0]])

In [ ]:
v3 = np.array([[0],[0],[0],[0],[0],[-1]])
v2 = np.array([[0],[0],[-1],[4],[2],[0]])
v1 = np.array([[0],[0],[0],[0],[1],[0]])
T = skewtomatrix(v2)

r = T[:3,:3]
p = T[0:3,3]
A_u = np.concatenate((r,np.zeros((3,3),int)), axis=1)
A_d = np.concatenate(((skew(p) @ r),r), axis=1)
a=np.concatenate((A_u,A_d), axis=0)
j1 = v1
a


array([[ 0,  1,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, -1,  0,  0],
       [-4, -2,  0,  0,  0,  0]])

1

In [ ]:
a= np.array([[0],[1],[0]])
b= np.array([[0],[2],[2]])
-skew(a) @ b

array([[-2],
       [ 0],
       [ 0]])

In [ ]:
np.array([[0],[1],[0],[-2],[0],[0]])

array([[ 0],
       [ 1],
       [ 0],
       [-2],
       [ 0],
       [ 0]])

2

In [ ]:
a= np.array([[0],[1],[0]])
b= np.array([[-2],[0],[0]])
-skew(a) @ b

array([[ 0],
       [ 0],
       [-2]])

In [ ]:
np.array([[0],[0],[0],[0],[1],[0]]) * -0.03

array([[-0.  ],
       [-0.  ],
       [-0.  ],
       [-0.  ],
       [-0.03],
       [-0.  ]])

3

Spatial J body twist

In [ ]:
import numpy as np

theta = np.array([[0.95000000], [-0.98000000], [0.73000000], [-0.38000000], [-0.13000000], [-0.10000000], [0.48000000], [0.45000000]])
dtheta = np.array([[-0.78000000], [0.40000000], [0.34000000], [-0.97000000], [-0.20000000], [0.44000000], [0.83000000], [-0.98000000]])
jacobian = np.array([[-1.00000000, 0.00000000, 0.00000000, -0.66686964, 0.00000000,  0.00000000, -0.27640044, -0.91106907], [0.00000000, 0.00000000, -0.81341550, -0.43345535, 0.00000000,  0.00000000, -0.61150764, -0.07879899], [0.00000000, 0.00000000, -0.58168309, 0.60613641, 0.00000000, 0.00000000,  -0.74139139, 0.40465277], [0.00000000, 0.00000000, -1.62683101, -1.62698859, -0.27640044,  0.69201711, 2.86867549, -4.01399389], [2.00000000, -0.81341550, 1.16336618, -1.10969964, -0.61150764,  -0.66194778, 4.69512184, -1.55262968], [0.00000000, -0.58168309, -1.62683101, -2.58356782, -0.74139139,  0.28798863, -4.94206717, -9.33978871]])
T_1in0 = np.array([[-0.91106907, 0.11584143, -0.39564366, 6.57470535], [-0.07879899, 0.89308081, 0.44294173, -7.91668657], [0.40465277, 0.43472684, -0.80453012, -0.24362540], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])


t01ad= toadjoint(np.transpose(T_1in0))
Vs=jacobian @ dtheta
t01ad @ Vs

array([[-2.60925529],
       [-0.79515097],
       [ 0.49236603],
       [-4.54457687],
       [ 8.27423812],
       [-6.57312585]])

In [ ]:
import numpy as np

theta = np.array([[-0.88000000], [-0.19000000], [0.44000000], [0.71000000], [0.39000000], [0.38000000], [0.74000000], [0.58000000]])
dtheta = np.array([[-0.59000000], [-0.63000000], [-0.12000000], [-0.68000000], [0.22000000], [0.70000000], [-0.20000000], [0.03000000]])
jacobian = np.array([[0.00000000, 0.63715114, 0.00000000, 0.75686884, -0.52570446,  -0.84766567, -0.84766567, -0.16477454], [0.00000000, -0.77073888, 0.00000000, 0.62568512, 0.41113869,  -0.32666155, -0.32666155, -0.58688930], [1.00000000, 0.00000000, 0.00000000, -0.18885889, -0.74471457,  0.41803725, 0.41803725, -0.79272335], [-2.00000000, 3.08295552, 0.63715114, -2.06097591, -2.23243197,  1.24241193, 0.71981263, -1.61707368], [0.00000000, 2.54860458, -0.77073888, 3.08042130, 2.08357160,  -1.04158685, 0.84406121, -1.23024623], [0.00000000, 1.27430229, 0.00000000, 1.94581955, 2.72619392, 1.70535898,  2.11914800, 1.24693049]])
T_1in0 = np.array([[0.04271813, 0.98540576, -0.16477454, -1.92491016], [0.79870858, -0.13276130, -0.58688930, 0.71140436], [-0.60019978, -0.10653602, -0.79272335, -1.79442160], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

t01ad= toadjoint(np.transpose(T_1in0))
Vs=jacobian @ dtheta
t01ad @ Vs

array([[ 0.17753293],
       [-1.38826321],
       [ 0.60742636],
       [-2.79867902],
       [ 1.35671184],
       [ 2.84349303]])

In [ ]:
t01ad= toadjoint(T_1in0)
Vs=jacobian @ dtheta
t01ad @ Vs

array([[-0.01980414],
       [-0.90415055],
       [ 1.22877135],
       [-4.62248998],
       [ 3.96303451],
       [ 2.31004503]])

The schematic of a robot with 8 joints (in the zero position) is shown above. Frame 0 is fixed to the base. Frame 1 is fixed to the end-effector. Denote the joint variables together by 
. We are given the space Jacobian of the end effector, the velocities of the joints 
 and the pose of the end-effector in frame 0: 
. Compute the body twist of the end-effector.

In [ ]:
def adt(m):    #Adjoint matrix
    r = m[0:3,0:3]
    p = m[0:3,3:4]
    p_ = skew(p)
    t1=p_.dot(r)
    t2=np.concatenate((r,t1),axis=0)
    t3=np.zeros((3,3))
    t4=np.concatenate((t3,r),axis=0)
    return np.concatenate((t2,t4), axis=1)

In [ ]:
import numpy as np

theta = np.array([[-0.88000000], [-0.19000000], [0.44000000], [0.71000000], [0.39000000], [0.38000000], [0.74000000], [0.58000000]])
dtheta = np.array([[-0.59000000], [-0.63000000], [-0.12000000], [-0.68000000], [0.22000000], [0.70000000], [-0.20000000], [0.03000000]])
jacobian = np.array([[0.00000000, 0.63715114, 0.00000000, 0.75686884, -0.52570446,  -0.84766567, -0.84766567, -0.16477454], [0.00000000, -0.77073888, 0.00000000, 0.62568512, 0.41113869,  -0.32666155, -0.32666155, -0.58688930], [1.00000000, 0.00000000, 0.00000000, -0.18885889, -0.74471457,  0.41803725, 0.41803725, -0.79272335], [-2.00000000, 3.08295552, 0.63715114, -2.06097591, -2.23243197,  1.24241193, 0.71981263, -1.61707368], [0.00000000, 2.54860458, -0.77073888, 3.08042130, 2.08357160,  -1.04158685, 0.84406121, -1.23024623], [0.00000000, 1.27430229, 0.00000000, 1.94581955, 2.72619392, 1.70535898,  2.11914800, 1.24693049]])
T_1in0 = np.array([[0.04271813, 0.98540576, -0.16477454, -1.92491016], [0.79870858, -0.13276130, -0.58688930, 0.71140436], [-0.60019978, -0.10653602, -0.79272335, -1.79442160], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

In [ ]:
Ti=sc.inv(T_1in0)
a=adt(Ti)
a@(jacobian@dtheta)

array([[ 0.17753292],
       [-1.38826321],
       [ 0.60742635],
       [-3.54073343],
       [ 2.07138826],
       [ 4.69375529]])

In [ ]:
import numpy as np

theta = np.array([[0.39000000], [-0.14000000], [0.13000000], [0.00000000], [0.94000000], [0.41000000], [0.31000000], [-0.02000000]])
dtheta = np.array([[0.33000000], [-0.17000000], [0.82000000], [0.06000000], [-0.37000000], [-0.87000000], [0.45000000], [0.03000000]])
jacobian = np.array([[0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000], [-1.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  -1.00000000, 0.00000000, 0.00000000], [2.00000000, -0.38018842, 0.00000000, 0.38018842, 0.38018842,  -2.36947356, 0.71735609, 0.71735609], [-2.00000000, -0.92490906, 0.00000000, 0.92490906, 0.92490906,  -4.52865592, 0.69670671, 0.69670671], [0.00000000, 0.00000000, -1.00000000, 0.00000000, 0.00000000, 0.00000000,  0.00000000, 0.00000000]])
T_1in0 = np.array([[0.71735609, 0.00000000, 0.69670671, -0.01648611], [0.69670671, 0.00000000, -0.71735609, 6.75175877], [0.00000000, 1.00000000, 0.00000000, -0.13000000], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
Ti=sc.inv(T_1in0)
a=adt(Ti)
a@(jacobian@dtheta)

array([[ 0.        ],
       [ 0.54      ],
       [ 0.        ],
       [ 1.96734909],
       [-0.82      ],
       [-2.93479741]])

The schematic of a robot with 9 joints (in the zero position) is shown above. Frame 0 is fixed to the base. Frame 1 is fixed to the end-effector. Denote the joint variables together by 
. We are given the body Jacobian of the end effector, the velocities of the joints 
 and the pose of the end-effector in frame 0: 
. Compute the spatial twist of the end-effector.

In [ ]:
import numpy as np

theta = np.array([[0.12000000], [-0.67000000], [0.10000000], [-0.06000000], [-0.98000000], [0.97000000], [-0.49000000], [0.82000000], [0.14000000]])
dtheta = np.array([[0.32000000], [-0.85000000], [0.42000000], [0.85000000], [0.60000000], [-0.01000000], [0.72000000], [-0.70000000], [-0.45000000]])
jacobian = np.array([[0.00000000, -0.99500417, 0.00000000, -1.00000000, 0.00000000,  0.00000000, 0.00000000, 1.00000000, 0.00000000], [0.00000000, -0.06360898, -0.77073888, -0.00000000, 0.00000000,  0.00000000, 0.00000000, 0.00000000, 0.00000000], [0.00000000, 0.07694550, -0.63715114, 0.00000000, 0.00000000, 0.00000000,  0.00000000, -0.00000000, 0.00000000], [0.06199515, -0.37165272, 6.61992782, -0.00000000, 1.00000000,  1.00000000, 0.00000000, 0.00000000, 0.00000000], [-0.99780710, -2.25575131, -3.81653535, -2.73029493, 0.00000000,  0.00000000, -0.73114583, 0.14000000, 0.00000000], [-0.02318592, -6.67072231, 4.61672588, -7.08714629, -0.00000000,  -0.00000000, -0.68222121, 4.00000000, -1.00000000]])
T_1in0 = np.array([[-0.99500417, -0.06360898, 0.07694550, -0.62096496], [-0.07825159, 0.01829984, -0.99676567, 0.38243087], [0.06199515, -0.99780710, -0.02318592, -6.51694952], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])



t01ad= toadjoint(T_1in0)
Vs=jacobian @ dtheta
t01ad @ Vs

array([[ 0.69225645],
       [ 0.38210409],
       [ 0.23311261],
       [-1.01787174],
       [-3.45117239],
       [ 2.70060528]])

4

In [ ]:
a= np.array([[1],[0],[0]])
b= np.array([[0],[-2],[0]])
-skew(a) @ b


array([[0],
       [0],
       [2]])

In [ ]:
b1= np.array([[0],[1],[0],[0],[0],[0]])
b2= np.array([[0],[1],[0],[0],[0],[0]])
b3= np.array([[1],[0],[0],[0],[0],[2]])

theta = np.array([[0.48000000], [-0.45000000], [0.54000000]])

m=  [[0,1,0,-2],[0,0,1,-6],[-1,0,0,0],[0,0,0,1]]

In [ ]:
j1= b1

In [ ]:
j2 = toadjoint(sc.expm(skewtomatrix(b1)*theta[1])) @ b2

In [ ]:
j3 = toadjoint(sc.expm(skewtomatrix(b2)*theta[2]) @ sc.expm(skewtomatrix(b1)*theta[1])) @ b3

In [ ]:
np.concatenate((j1,j2,j3), axis=1)

array([[ 0.        ,  0.        ,  0.99595273],
       [ 1.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -0.08987855],
       [ 0.        ,  0.        ,  0.1797571 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.99190547]])

In [ ]:
a= np.array([[0],[0],[1]])
b= np.array([[0],[-2],[6]])
-skew(a) @ b

array([[-2],
       [ 0],
       [ 0]])

In [ ]:
from scipy.linalg import expm
import numpy as np

theta = np.array([[-0.47000000], [0.57000000], [0.72000000]])

s1 = np.array([[0],[0],[0],[0],[0],[1]])
s2 = np.array([[0],[0],[0],[-1],[0],[0]])
s3 = np.array([[0],[0],[1],[-2],[0],[0]])


def twist(vector):
    vector=np.array(vector)
    return np.array([[0, -vector.item(2), vector.item(1),vector.item(3)],
                     [vector.item(2), 0, -vector.item(0),vector.item(4)],
                     [-vector.item(1), vector.item(0), 0,vector.item(5)],
                    [0,0,0,0]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])


    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

J1=s1;
J2=adjform(expm(twist(s1*theta.item(0))))@s2
J3=adjform((expm(twist(s1*theta.item(0))))@(sc.expm(twist(s2*theta.item(1)))))@s3

print(repr(J1))
print(repr(J2))
print(repr(J3))


ans = np.array([[J1.item(0),J2.item(0),J3.item(0)],
                     [J1.item(1),J2.item(1),J3.item(1)],
                     [J1.item(2),J2.item(2),J3.item(2)],
                     [J1.item(3),J2.item(3),J3.item(3)],
                     [J1.item(4),J2.item(4),J3.item(4)],
                     [J1.item(5),J2.item(5),J3.item(5)]]);

print(repr(ans))

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1]])
array([[ 0.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 0.]])
array([[ 0.  ],
       [ 0.  ],
       [ 1.  ],
       [-2.  ],
       [ 0.57],
       [ 0.  ]])
array([[ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ],
       [ 0.  , -1.  , -2.  ],
       [ 0.  ,  0.  ,  0.57],
       [ 1.  ,  0.  ,  0.  ]])


In [ ]:
a= np.array([[0],[0],[-1]])
b= np.array([[2],[0],[-4]])

np.concatenate((a,-skew(a) @ b),axis =0)

array([[ 0],
       [ 0],
       [-1],
       [ 0],
       [ 2],
       [ 0]])

In [ ]:
from scipy.linalg import expm
import numpy as np

theta = np.array([[-0.74000000], [-0.32000000], [0.30000000]])

s1 = np.array(
       [[1],
       [0],
       [0],
       [0],
       [0],
       [0]]
       )
s2 = np.array(
       [[0],
       [0],
       [0],
       [0],
       [-1],
       [0]]
       )
s3 = np.array(
       [[0],
       [ 0],
       [-1],
       [ 0],
       [ 2],
       [ 0]]
       )


def twist(vector):
    vector=np.array(vector)
    return np.array([[0, -vector.item(2), vector.item(1),vector.item(3)],
                     [vector.item(2), 0, -vector.item(0),vector.item(4)],
                     [-vector.item(1), vector.item(0), 0,vector.item(5)],
                    [0,0,0,0]])

def adjform(vector):
    vector=np.array(vector);
    
    def skew(vector):
        vector = np.array(vector)
        return np.array([[0, -vector.item(2), vector.item(1)],
                     [vector.item(2), 0, -vector.item(0)],
                     [-vector.item(1), vector.item(0), 0]])
    def retR(vector):
        vector=np.array(vector)
        return np.array([[vector.item(0),vector.item(1),vector.item(2)],
                    [vector.item(4),vector.item(5),vector.item(6)],
                    [vector.item(8),vector.item(9),vector.item(10)]])

    def retP(vector):
        vector=np.array(vector)
        return np.array([[vector.item(3)],
                    [vector.item(7)],
                    [vector.item(11)]])


    R=retR(vector);
    p=retP(vector);
    pt=skew(p)@R;

    return np.array([[vector.item(0),vector.item(1),vector.item(2),0,0,0],
                     [vector.item(4),vector.item(5),vector.item(6),0,0,0],
                     [vector.item(8),vector.item(9),vector.item(10),0,0,0],
                     [pt.item(0),pt.item(1),pt.item(2),vector.item(0),vector.item(1),vector.item(2)],
                     [pt.item(3),pt.item(4),pt.item(5),vector.item(4),vector.item(5),vector.item(6)],
                     [pt.item(6),pt.item(7),pt.item(8),vector.item(8),vector.item(9),vector.item(10)]]);

J1=s1;
J2=adjform(expm(twist(s1*theta.item(0))))@s2
J3=adjform((expm(twist(s1*theta.item(0))))@(sc.expm(twist(s2*theta.item(1)))))@s3

print(repr(J1))
print(repr(J2))
print(repr(J3))


ans = np.array([[J1.item(0),J2.item(0),J3.item(0)],
                     [J1.item(1),J2.item(1),J3.item(1)],
                     [J1.item(2),J2.item(2),J3.item(2)],
                     [J1.item(3),J2.item(3),J3.item(3)],
                     [J1.item(4),J2.item(4),J3.item(4)],
                     [J1.item(5),J2.item(5),J3.item(5)]]);

print(repr(ans))

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0]])
array([[ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [-0.73846856],
       [ 0.67428791]])
array([[ 0.        ],
       [-0.67428791],
       [-0.73846856],
       [-0.32      ],
       [ 1.47693712],
       [-1.34857582]])
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.67428791],
       [ 0.        ,  0.        , -0.73846856],
       [ 0.        ,  0.        , -0.32      ],
       [ 0.        , -0.73846856,  1.47693712],
       [ 0.        ,  0.67428791, -1.34857582]])


In [ ]:
T01 = (sc.expm(skewtomatrix(s1) * theta[0]) @ sc.expm(skewtomatrix(s2) * theta[1]) @ sc.expm(skewtomatrix(s3) * theta[2])) @ M
T01

jb= toadjoint(sc.inv(T01)) @ ans
jb

array([[ 9.21060994e-01, -2.87086148e-17,  1.00000000e+00],
       [-3.81655902e-01,  1.98669331e-01,  1.15169207e-18],
       [-7.73654815e-02, -9.80066578e-01, -4.91961136e-18],
       [-7.44283494e-17, -5.11534674e+00, -7.77665277e-17],
       [ 3.65973143e-01, -7.22160877e+00,  1.41360117e+00],
       [-1.80540219e+00, -1.46389257e+00, -6.97351353e+00]])

In [ ]:
theta = np.array([[-0.47000000], [0.57000000], [0.72000000]])

s1 = np.array([[0],[0],[0],[0],[1],[0]])
s2 = np.array([[0],[0],[0],[1],[0],[0]])
s3 = np.array([[0],[1],[0],[0],[0],[0]])

j1=s1
j2=toadjoint(sc.expm(-skewtomatrix(s1)*-0.47000000)) @ s2
j3=toadjoint(sc.expm(-skewtomatrix(s2)*0.57000000) @sc.expm(-skewtomatrix(s1)*-0.47000000)) @ s2
np.concatenate((j1,j2,j3), axis=1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])